### PR TITLE
build for 2.14.0 LTR

### PR DESCRIPTION
**Pull request by luipir**
can be cleaned more to remove unecessary imports

### CODE REVIEW

**Comment by timlinux** [comment]
Wow thanks so much for the patch @luipir !

**Comment by luipir** [comment]
thanks to you to share the base,

well I have to be cleaned to remove more packages.

there where some errors in the Dockerfiles and some lack of packages useful for python plugins.
the docker produced is really big 1.8GB.. but probably it will be smaller when a debian package will be available.

did you plan to use a https://hub.docker.com/_/alpine/  instead of a big ubuntu?

**Comment by timlinux** [comment]
@luipir I don't intend to use packaged QGIS since the packages are hard to access historically. My intent is to provide a platform that lets you deploy a known good collection of containers with specified versions. So if e.g. you want to deploy QGIS Server based on 2.8.x you should be able to do it (and have security updates applied to the base platform via docker hub).

So my intention is to always build from source on top of ubuntu (or a smaller base system would be fine) and have the images available at https://hub.docker.com/r/kartoza/qgis-desktop/

My biggest blocker is that docker hub always times out fetching network packages - I still need to figure out how to resolve that. If you look on the above hub, the images are actually much smaller - ~680mb - though I agree it would be nice to make it smaller still.

Another thing to mention is that the next generation QGIS server containers I am working on will inherit from this QGIS desktop image and just add a web browser in front, so we get good container re-use for server deploys.

Building these images is just a hobby for me and the last few months I had no time to work on it, but I look forward to having a bit of time to get them all working beautifully - they add a lot of possibilities for the future!

**Comment by timlinux** [comment]
By the way your PR is failing on hub with 

```
Starting to clone
Cloning into 'b7ukqzy3gsaq2etnqttmhik'...
Cloning done
Dockerfile not found at 2.14
```

https://hub.docker.com/r/kartoza/qgis-desktop/builds/b7ukqzy3gsaq2etnqttmhik/

**Comment by timlinux** [comment]
Ah its because I need to merge your changes to master! Will do that in the morning!

**Comment by timlinux** [comment]
Correction to above - I am building on top of debian, not ubuntu.

**Comment by luipir** [comment]
you're right sorry :)

**Pull request merged**
